spring.application.name=auto-form
server.port=${SERVER_PORT:8080}
logging.level.ru.bell.auto_form=${LOG_LEVEL:INFO}
spring.task.scheduling.pool.size=2

# yandex.client_id - the client application ID received when registering the application in Yandex.OAuth
# yandex.secret_client_id - the secret key of the client application received when registering the application in Yandex.OAuth.
# yandex.redirect_uri - the redirect URI that Yandex.OAuth returns the user to after successful authorization.
# yandex.survey_id - ID of the Yandex form.
# yandex.files_directory - directory on the first yandex.disk for storing files from form answers (for example, /foldir)
# yandex.table_answers_name - file name of the answers table on the first yandex.disk (for example, answers.xlsx)

yandex.client_id=${YANDEX_CLIENT_ID}
yandex.secret_client_id=${YANDEX_SECRET_CLIENT_ID}
yandex.redirect_uri=${YANDEX_REDIRECT_URI:http://localhost:8080/auth/back}
yandex.survey_id=${YANDEX_SURVEY_ID}
yandex.files_directory=${YANDEX_FILES_DIRECTORY:/foldir}
yandex.csv_token_path=${CSV_TOKEN_PATH:/home/$USER/data/tokenStorage.csv}

# yandex-two.url_disk - URL of the table on the second yandex.disk (for example, https://disk.yandex.ru/i/**)

yandex-two.url_disk=${YANDEX_TWO_URL_DISK}

# current.polling_time_milliseconds - time periodic check yandex.form (in milliseconds)

current.polling_time_milliseconds=${CURRENT_POLLING_TIME_MILLISECONDS:43200000}
