spring.application.name=auto-form

# yandex.token - the OAuth token for the first yandex.disk
# yandex.survey_id - ID of the Yandex form.
# yandex.files_directory - directory on the first yandex.disk for storing files from form answers (for example, /foldir)
# yandex.table_answers_name - file name of the answers table on the first yandex.disk (for example, answers.xlsx)

yandex.token=
yandex.survey_id=
yandex.files_directory=
yandex.table_answers_name=

# yandex-two.url_disk - URL of the table on the second yandex.disk (for example, https://disk.yandex.ru/i/**)

yandex-two.url_disk=

# current.download_dir - local directory for temporary file storage (for example, C:\\projects\\files)
# current.polling_time_milliseconds - time periodic check yandex.form (in milliseconds)

current.download_dir=
current.polling_time_milliseconds=43200000
